.TH "APT" 8 "14 Jun 2006" "APT-RPM" "apt"
.SH NAME
apt - Advanced Package Tool

.SH DESCRIPTION
APT is a management system for software packages.  Originally written for Debian and the deb package format, APT was ported and became APT-RPM to manage the \fBrpm\fR(8) package format.  APT-RPM can be used by any RPM-based distribution, such as Conectiva, Red Hat, SUSE, ALT-Linux, etc.
.LP
For further information on how to use APT, refer to \fBapt-get\fR(8) or visit http://apt-rpm.org/.

.SH SEE ALSO
\fBapt-cache\fR(8), \fBapt-get\fR(8), \fBapt-cdrom\fR(8),
\fIsources.list\fR(5), \fIapt.conf\fR(5), \fBapt-config\fR(8),
\fIapt_preferences\fR(5)

.SH "BUGS"
Reporting bugs in APT-RPM is best done in the APT-RPM mailinglist at
http://apt-rpm.org/mailinglist.shtml.

.SH "AUTHOR"
Maintainer and contributor information can be found in the credits page
http://apt-rpm.org/about.shtml of APT-RPM.
